### ISSUE TITLE
Grammar in README.md

### ISSUE THREAD

**Issue by jbrucker** [Sahanon-P/Sahanon-P#1]
Since you put effort into writing your profile README, here are some grammar edits, in case you care about that...

> Programming is like a magic.
should be "like magic" (no "a")

> specific instruction
use plural "instructions", and interesting way of looking at programming.

> "About Me:"
omit colon.  Also omit colon in other section titles.  If it was an ordinary paragraph, colon would be OK, but not when it is a section header.

needs an update re senior project status.

> Feel free to ask me about anything related to software (or else)

"Feel free to ask me anything related to software (or other)"

> Social Account:

"Social Accounts"

What a tech stack! 
You know a lot more than I do.

**Comment by Sahanon-P** [comment]
Thanks for your suggestion. It's actually make my profile look better!
